### ISSUE TITLE
"npm install iobroker.mihome-vacuum" does not work

### ISSUE THREAD

**Issue by virgin09** [ioBroker/ioBroker.mihome-vacuum#1]
tried to install this way but continiously  get error "'iobroker.mihome-vacuum' is not in the npm registry."

Please check. Thanks

**Comment by GermanBluefox** [comment]
Just now it must be installed from git. Because the complex codes finding I
am thinking about if it should be on npm or not.

npm i https://github.com/ioBroker/ioBroker.mihome-vacuum/tarball/master





5 Фев 2017 г. 16:52 пользователь "virgin09" <notifications@github.com>
написал:

**Comment by virgin09** [comment]
ok, thanks
