### ISSUE TITLE
Frage zu npm

### ISSUE THREAD

**Issue by realhoffi** [ioBroker/ioBroker.mihome-vacuum#31]
Hi,

ich würde gerne deine Bibliothek nutzen, leider hab ich mal gar keinen Schimmer, wie ich die in mein Projekt einbinden soll.
Ich nutze auch NodeJs und benötige mal eine kleine Hilfe, bzw. StartUp Skript, wie es zu benutzen ist in meiner Server.js

**Comment by Apollon77** [comment]
Dies ist keine Bibliothek in dem Sinne,es ist ein Adapter für ioBroker, ein Home-Automation-System. Von daher ist es keine klassische npm Library.
Du brauchst ioBroker als grundsystem
