### ISSUE TITLE
Make adapter ready for Admin v3

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/ioBroker.mihome-vacuum#32]
For Admin3 some changes are needed: see http://forum.iobroker.net/viewtopic.php?f=24&t=10268

**Comment by MeisterTR** [comment]
in a few days i get my second generation, then i will implement the new version, sound level and the changes for the admin

**Comment by GermanBluefox** [comment]
Cool.

**Comment by GermanBluefox** [comment]
I should to get the second version too... But I don't known when.

**Comment by MeisterTR** [comment]
could be closed
