### ISSUE TITLE
Widget funktioniert nur per Maus, nicht per Widget

### ISSUE THREAD

**Issue by LeRob** [ioBroker/ioBroker.mihome-vacuum#42]
Hi,
wenn ich iobroker.vis auf meinem Surface aufrufe kann ich per Mausklick die Buttons betätigen. Wenn ich per Touch draufdrücke oder auf dem Tablet per Finger wird nichts erkannt.
Ich hab zwar noch nie gesehen, dass ein Unterschied zw. Finger und Mausklick gemacht wird, aber hier ist es definitv der Fall.
Mausklick funktioniert.
Fingereingabe nicht.

**Comment by LeRob** [comment]
Scheint ein Problem von VIS zu sein und nicht vom Widget allgemein.

**Comment by GermanBluefox** [comment]
I must check it.

**Comment by LeRob** [comment]
Only appears when swipe navigation is used.

**Comment by MeisterTR** [comment]
so its an issue for vis i think..

**Comment by GermanBluefox** [comment]
Ne.... it is for widget. We schould add to mousedown and mouseup two
Events: touchstart and touchend

пт, 27 июл. 2018 г., 20:08 MeisterTR <notifications@github.com>:
