### ISSUE TITLE
Check if token is correct

### ISSUE THREAD

**Issue by BuZZy1337** [ioBroker/ioBroker.mihome-vacuum#45]
The adapter should check if the token is correct or not before setting info.connection to true

**Comment by MeisterTR** [comment]
that is not so easy as it seems. There are two cases when the robot did not answer. 

First case: 
he did not thrust the new client (but the token is right), then the robot did not answer on the messages and it coult take about 10 minutes til the robot response on messages. 

Second case: The token is wrong.

The only way to check the token, is about the response, but if you set the connection to false e.g after 10 messages wihtout response, the user tries to restart the adapter or change the token (result: message id change from eg 100 to 0) if the user does this a few times the robot puts the client on a blacklist and the only way to reset it, is a reboot of the robot.

so there is no reliable way to check the token.

**Comment by BuZZy1337** [comment]
Okay, thanks for your answer. I will investigate that in the firmware when i have some free time for that.. Maybe there is another way to check the token.. We will see.. ☺️
