### ISSUE TITLE
Zone Cleanup and Goto y-value changed

### ISSUE THREAD

**Issue by GrudonR** [ioBroker/ioBroker.mihome-vacuum#51]
The values for the y coordinate changes for zone cleanup and goto.
For example one point for goto could be [26000,24000] but the same point for zone cleanup would be [26000,26000,x2,y2].

Just found it out after testing it.
Maybe a hint in the documentation could help some people.

**Comment by BuZZy1337** [comment]
On my cleaner i noticed the scheme is like that:
x1 , y2 , x2 , y1

Where x1 and y1 are the coordinates for the upper left corner
and y2, x2 for the lower right corner..

If my GoTo-Point is
[**26600**,**23900**]
and i want the upper left corner of the zoneClean rectangle to be at the exact same point
then it is:
x1 , y2 , x2 , y1
[**26600**,y2,x2,**23900**]

x1 changes if i move the upper left corner horizontally on the map (left/right)
y2 changes if i move the lower right corner vertically on the map (up/down)
x2 changes if i move the lower right corner horizontally on the map (left/right)
y1 changes if i move the upper left corner vertically on the map (up/down)

I am not sure if the angle of the Maprotation has anything to do with that but i will investigate that and change the documentation after that. ☺️

**Comment by stef-73** [comment]
Mhh, here the map coords are as decribed: x1,y1 is lower left, x2,y2 is upper right. And zone and goto points match.
Strange

**Comment by BuZZy1337** [comment]
Im closing this issue, because there is nothing we can do about the map rotation at the moment..
