### ISSUE TITLE
pls help 

### ISSUE THREAD

**Issue by tigerlampe** [ioBroker/ioBroker.mihome-vacuum#54]
i just got a yellow sign im sure i used the right ip address and also get the token 
i dont know where the error is comming from 
i use the roborock  ( mi vacuum 2 )

**Comment by Apollon77** [comment]
which error is it?

**Comment by tigerlampe** [comment]
i just get it yellow and can not controll it over iobroker

**Comment by tigerlampe** [comment]
mihome-vacuum.0 | 2018-09-17 15:54:55.334 | info | Cloud control disabled
-- | -- | -- | --
mihome-vacuum.0 | 2018-09-17 15:54:55.334 | info | Expert mode disabled, states deleded

**Comment by BuZZy1337** [comment]
Really sure that the ip is correct?
Is your iobroker and vacuum cleaner in the same network?

**Comment by tigerlampe** [comment]
yeah im pretty sure

**Comment by tigerlampe** [comment]
![iobroker](https://user-images.githubusercontent.com/43344649/45627951-50998f80-ba93-11e8-8e9e-faa65a636232.JPG)
![router](https://user-images.githubusercontent.com/43344649/45627952-50998f80-ba93-11e8-873c-2461d3e83584.jpg)

**Comment by tigerlampe** [comment]
now i tryed a restart of the server cuz my hue adapter also not works and now its red

**Comment by BuZZy1337** [comment]
The Vacuum cleaner sometimes ignores new connections for a couple of time..
Try to start the adapter and let it run for about 30 Minutes and see if it works..

**Comment by tigerlampe** [comment]
its still red .... :/

**Comment by BuZZy1337** [comment]
Please set the instance loglevel to "debug" and check the logs again.

To set the loglevel to debug you have to go to the Instance page in iobroker, activate the "expert view" and change the loglevel in the table (on the mihome-vacuum row) from info to debug.

**Comment by BuZZy1337** [comment]
Any news regarding this issue?

**Comment by tigerlampe** [comment]
sry i had no time yesterday .... I ended the admin unintentionally , now i restart it via  the vis and now its green .... i dont know how  but its green :D

tanks for your time :)

**Comment by tigerlampe** [comment]
im now tryed the widget for the cleaner and just the find function works
any idea 
did i some fail ?
![new](https://user-images.githubusercontent.com/43344649/45709816-3809a200-bb85-11e8-8429-332a3027a01c.JPG)

**Comment by BuZZy1337** [comment]
"ID für start" is wrong on your Screenshot.. Choose the "start" state for that.. Not the "go home".

**Comment by tigerlampe** [comment]
oh my shity  hahahhaha

**Comment by BuZZy1337** [comment]
... that sounds like "Whoooops.. Everything is working now!" ..? 😆

**Comment by tigerlampe** [comment]
yeah

**Comment by tigerlampe** [comment]
thank u
