### ISSUE TITLE
Zone Cleaning Stops after one Minute

### ISSUE THREAD

**Issue by andglaser** [ioBroker/ioBroker.mihome-vacuum#57]
Hello,

i´ve updatet to Roborock Frimware 3.3.9_001632 and use mihome-vacuum V.1.1.5
Zone Cleaning stops after one minute and the roborock goes back to dock without finishing job.

Greating

**Comment by andglaser** [comment]
I copied the coordinates from Flole and remove the brackets like JoJ123.
Now it works fine

**Comment by GermanBluefox** [comment]
> Hi,
> same for me. I take the coordinates out of the FloleVac App.
> And he starts, drive 20cm forward and stop the cleaning.
> 
> My Problem was I used an old tutorial and they wrote to put:
> [[26092,22991,28092,25641,1]] with two [] brackets.
> 
> With one bracket it's working fine :)

Can we fix this tutorial?

**Comment by JoJ123** [comment]
https://www.roboter-forum.com/index.php?thread/26292-zonen-reinigung-per-iobroker-alexa-steuern-schritt-f%C3%BCr-schritt-anleitung/&postID=389666#post389666

It's described with one bracket there, but when you copy more then one area you think that the second bracket is mandatory.

So maybe we should just put there a warning to just use one bracket pair.

**Comment by BuZZy1337** [comment]
I will change the behavior of the adapter so it will accept [[..]], [..] and even the coordinates without brackets at all..

**Comment by JoJ123** [comment]
That's the best ;) Thx!

BuZZy1337 <notifications@github.com> schrieb am Mo., 22. Okt. 2018, 15:28:
