### ISSUE TITLE
Does not work anymore

### ISSUE THREAD

**Issue by hildi44** [ioBroker/ioBroker.mihome-vacuum#59]
Tells me invalid or unexpeted token since new Adroid App Vesion 5.4.24

Seems that token was changed, but also the new token (read out with the russian app) did not work.

**Comment by BuZZy1337** [comment]
I got the update for the MiHome App yesterday (5.4.26)...
The Adapter is working normally..
Token does not change by itself or during a simple app update.

Can you please provide a screenshot of the log/error messages?

**Comment by hildi44** [comment]
![image](https://user-images.githubusercontent.com/44669277/47855113-ebe88900-dde3-11e8-9055-5be36c98fccd.png)


Hi, here is the screenshot... Thank you for your support....

**Comment by hildi44** [comment]
Thank you, that solved my problem. Adapter is working fine again.
