### ISSUE TITLE
Zone cleaning on V1 Xiaomi with current firmware

### ISSUE THREAD

**Issue by Cumulus7** [ioBroker/ioBroker.mihome-vacuum#62]
Hi,
i am unable to find the zone-cleaning part in the objects browser.
Do i overlook something?

I have a Xiaomi V1 international Version with current firmware, which does zone-cleaning just fine via both the Xiaomi and FloleVac-Apps.

THX
Markus

**Comment by BuZZy1337** [comment]
Did you successfully connect your vacuum to the adapter in ioBroker? Are you able to start and stop the Vacuumcleaner via ioBroker?

Try to restart the adapter.. Refresh the Browser.. (STRG+F5)..

Here is a Screenshot of the State..
![image](https://user-images.githubusercontent.com/6979405/49636628-6e77f000-fa03-11e8-809d-e82aa9848b88.png)

**Comment by Cumulus7** [comment]
Hi, 
thx for the fast response.
"zoneclean" is not shown here.

![image](https://user-images.githubusercontent.com/45620107/49636857-1a214000-fa04-11e8-941f-4e8d46712692.png)


Is there a difference built into the adapter to not show these controls for V1 robots?
They got these possibilities only later with a firmware update.

Addition: 
sending custom command 
`app_zoned_clean;[[24153,20570,26903,23520,1]]`
works just fine.

**Comment by BuZZy1337** [comment]
Hi,

the Adapter checks if the cleaner is a second generation device OR the firmware is newer than 3.3.9 - Build 3194 and then adds the State for Zonecleaning..

Which firmware is installed on your vacuum?

You could try to set the Loglevel of the adapter to debug and then post the log output here after the adapter restarted.

**Comment by Cumulus7** [comment]
I have Firmware 3.3.9_003170.
Seems that is too old.
THX - will do an update.

**Comment by BuZZy1337** [comment]
Yes, that is too old. Update via FloleVac App to minimum 3.3.9 - 3194.. Then please check again if the state is showing up. :relaxed:

**Comment by Cumulus7** [comment]
Yes, the option is there now!

Great support. THX a lot!

**Comment by Cumulus7** [comment]
One more thing:
When using `app_zoned_clean;[[24153,20570,26903,23520,1]]` it works just fine.
Inserting the same coordinates in the zone-clean state makes the robot start zone-cleaning and return to dock a few seconds later with "finished".

Any idea why that might be?

**Comment by Cumulus7** [comment]
See this blockly script:
![image](https://user-images.githubusercontent.com/45620107/49642069-4ba10800-fa12-11e8-8b49-038eb19b07a0.png)

**Comment by BuZZy1337** [comment]
You only need the "double brackets" [[ ]] at the send_command state.. At the normal zoneclean state you have to use "single brackets" [ ] 

For example 
[x, y, x, y, 1]
Or
[x, y, x, y, 1],[a, b, a, b, 1]

**Comment by Cumulus7** [comment]
🥇 
THX a lot. Will try that.

P.S: "OK Google, clean the kitchen" works awesome 👍. That is how home automation should work!
